### ISSUE TITLE
Custom SWF client

### ISSUE THREAD

**Issue by thomasklinger1234** [awslabs/flux-swf-client#23]
Hello,

I would like to provide a custom SWF client to the Flux library. Is this possible? My use case is that I want to use AWS XRay for the SWF client like this:

```

    @Bean
    fun provideSwfClient(): SwfClient {
        return SwfClient.builder()
            .credentialsProvider(EnvironmentVariableCredentialsProvider.create())
            .overrideConfiguration(
                ClientOverrideConfiguration.builder()
                    .addExecutionInterceptor(TracingInterceptor()) // This is the magic part
                    .build())
            .build()
    }
```

However, I did not see any examples and it seems that the library internally constructs its own client instance.

**Comment by danielgmyers** [comment]
This currently isn't possible, but I'll look at adding `ClientOverrideConfiguration` to `FluxCapacitorConfig` to let you configure this kind of client customization.

**Comment by thomasklinger1234** [comment]
> This currently isn't possible, but I'll look at adding `ClientOverrideConfiguration` to `FluxCapacitorConfig` to let you configure this kind of client customization.

That would be awesome!

**Comment by danielgmyers** [comment]
Version 2.0.3 with this change is now available from Maven Central :)
