### ISSUE TITLE
Parititioned step additional attributes get dropped if SWF throttles activity creation

### ISSUE THREAD

**Issue by danielgmyers** [awslabs/flux-swf-client#33]
There is a bug that happens when the following conditions are true:

a) The step is partitioned
b) The `@PartitionIdGenerator` method returns a `PartitionIdGeneratorResult` object that contains at least one additional attribute.
c) SWF fails scheduling one or more of the partitions (i.e. scheduled activity task rate exceed)

In this case, the additional attributes in the original PartitionIdGeneratorResult are lost for any partition attempt that was throttled. I haven't checked but it may also drop the attributes from earlier steps.

I've found comments in the code indicating that I had previously known this edge case existed, except it didn't matter because there was previously no way to add additional attributes from the partition id generator. This changed when I added `PartitionIdGeneratorResult`.

I'm working to confirm whether SWF handles the list of decisions from `RespondDecisionTaskCompleted` atomically; I suspect they don't. On that assumption, we'll need a solution that doesn't assume the first attempt of a partitioned step will always schedule all partitions together.

**Comment by danielgmyers** [comment]
After some discussion with @joeymarylander, we think we do need to go with that last "split the content across multiple markers" solution, for two main reasons.

First, creating a thousand markers feels wrong, and results in a lot of redundant data being stored in the workflow history, and potentially uses up a large chunk of the 25000 events-per-workflow maximum limit.

Second, splitting the data across multiple markers will not be necessary most of the time. 100 partitions each with 100-character partition IDs uses 10k total. Most of the use cases I'm aware of use either a small number of partitions (<10), or a very large number of partitions but with a very short partition id (e.g. 1000 partitions with a two-character prefix as the partition id).

We also considered compressing the list of partition IDs, but I'm not sure the extra complexity is worth the space savings. (A list of random alphanumeric strings compresses by about 25% with gzip.)

So the solution will look like this:

When the next step to be scheduled is a partitioned step, if there is not already a partition id generator result marker, we run the partition id generator, and put its output in a marker event. We respond to the decision task with that marker along with a decision indicating we want to send a "do another decision" signal to the workflow. (This is necessary because adding a marker event does not trigger a new decision by itself.)

If instead there is already a partition id generator result marker, we make a list of partitions that have not been successfully scheduled at least once. For each of those, we generate ScheduleActivityTask decisions, using the data from the marker as the source of partition IDs and additional attributes. For all other partitions, we follow the normal retry logic.

Additionally, we should change the existing logic for how to handle the "schedule activity task failed" state for a partition; instead of extracting the partition ID from the most recent attempt and retrying without input attributes, we determine the input (both the partition ID and the other attributes) based on the most recent successfully-executed attempt of the partition. Combined with the above logic for scheduling the first attempt of a partition, this should cover all of the cases where scheduling an activity execution has failed.

---

We also discussed backward compatibility; specifically, what happens if an application encounters this issue while also deploying an update to Flux that includes this bugfix.

Currently, a workflow in this bad state needs to be terminated and restarted. While it would be ideal if deploying this fix could automatically resolve the issue in all cases, we do not believe we can safely assume that the partition id generation logic can be re-run unless _none_ of the partitions were successfully scheduled. As such, this fix will include the following logic:

1) If the marker is missing but there is at least one successful scheduling attempt for every partition, proceed without the marker, using the first attempt of each partition as the source of truth. (This is the same as the logic called out in the "Additionally" section above.)
2) If the marker is missing but one or more partitions only has _failed_ scheduling attempts (that is, there has never been a successfully-scheduled first attempt), record a marker indicating that the workflow is broken and needs to be restarted, then avoid making more decisions for the workflow.
3) If the marker is missing, and there are failed scheduling attempts for one or more partitions, but _no_ successful scheduling attempts for any partitions, create a new partition id generator result marker and follow the normal process from there.

This minimizes the impacted users to only those who are affected by this bug _during_ the deployment of this fix.

**Comment by joeymarylander** [comment]
well said.

**Comment by danielgmyers** [comment]
I merged the main fix, now I just need to add the marker splitting logic for when the partition ID list is too big. My thought is to split the partition id list itself into chunks, with each marker containing a subset of the partition ids, such that each marker contains valid JSON on its own. I'd also add an extra field to the json indicating how many markers there are for validation purposes.

When reading the markers back from the history, I'd merge together the partition id lists from each of the markers. The additional attributes map would only be included in the first marker.

**Comment by danielgmyers** [comment]
This is fixed, and will be included in the next release.
